config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :blogs do
    collection do
      post 'confirm'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: {minimum: 6}

  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # protect_from_forgery
  def index
    @blog = Blog.all
    
  end

  def new
    @blog = Blog.new

  end

  def create
    @blog = current_user.blogs.build(get_params)
    @blog.save
    byebug
    redirect_to blogs_path
  end

  def confirm
    # @blog = Blog.new(get_params)
    # @blog.user_id = current_user.id
    @blog = current_user.blogs.build(get_params)
    render :new if @blog.invalid?
  end

  def show
  end

  def destroy
    set_blog
    @blog.destroy
    redirect_to blogs_path
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def get_params
    params.require(:blog).permit(:title, :content )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only:[:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new

    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only:[:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @blog = Blog.all
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bolgs_helper.rb
module BolgsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/confirm.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <%= form.label :title %>
  <%= @blog.title%>
  <%= form.hidden_field :title %>

  <%= form.label :content %>
  <%= @blog.content%>
  <%= form.hidden_field :content %>

  <%# <%= form.label :user_id %> %>
  <%# <%= @blog.user_id %> %>
  <%# <%= form.hidden_field :user_id %> %>



  <%= form.submit '送信' %>
<% end %>

app/views/blogs/edit.html.erb
a

app/views/blogs/index.html.erb
<%= link_to "作成", new_blog_path%>
<% @blog.each do |blog| %>

  <%= blog.title %>
  <%= blog.content %>
  <%= link_to 'show', blog_path(blog.id) %>
  <%= link_to 'edit', edit_blog_path(blog.id) %>
  <%= link_to 'delete', blog_path(blog.id) , method: :delete %>

<% end %>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true, url: confirm_blogs_path) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :content %>
  <%= form.text_field :content %>

  <%# <%= form.label :user_id %> %>
  <%# <%= form.text_field :user_id %> %>
  <%= form.submit %>

<% end %>


app/views/blogs/show.html.erb
a

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionLogin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <% if logged_in? %>
    <%= link_to "Profile", user_path(current_user.id)%>
    <%= link_to "logout", session_path(current_user.id), method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_path %>
    <%= link_to "Login", new_session_path %>
  <% end %>
  <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_with(model: @user,local: true, ) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>

  <%= f.submit "Create my account"%>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>
<% @blog.each do |blog| %>
<%# <%= blog.label :title %> %>
<% end %>
<%= link_to 'ブログを作成する', new_blog_path %>